// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"time"
)

// User represents a row from 'public.users'.
type User struct {
	ID         int            `json:"id"`          // id
	Email      string         `json:"email"`       // email
	FirstName  sql.NullString `json:"first_name"`  // first_name
	LastName   sql.NullString `json:"last_name"`   // last_name
	Password   string         `json:"password"`    // password
	ModifiedAt time.Time      `json:"modified_at"` // modified_at
	CreatedAt  time.Time      `json:"created_at"`  // created_at

	_exists, _deleted bool
}

type UserService interface {
	DoesUserExists(u *User) (bool, error)
	InsertUser(u *User) error
	UpdateUser(u *User) error
	UpsertUser(u *User) error
	DeleteUser(u *User) error
	GetAllUsers() ([]*User, error)
	GetChunkedUsers(limit int, offset int) ([]*User, error)
}

type UserServiceImpl struct {
	DB XODB
}

// Exists determines if the User exists in the database.
func (serviceImpl *UserServiceImpl) DoesUserExists(u *User) (bool, error) {
	panic("not yet implemented")
}

// Insert inserts the User to the database.
func (serviceImpl *UserServiceImpl) InsertUser(u *User) error {
	var err error

	// sql insert query, primary key provided by sequence
	const sqlstr = `INSERT INTO public.users (` +
		`email, first_name, last_name, password, modified_at, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt)
	err = serviceImpl.DB.QueryRow(sqlstr, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt).Scan(&u.ID)
	if err != nil {
		return err
	}

	return nil
}

// Update updates the User in the database.
func (serviceImpl *UserServiceImpl) UpdateUser(u *User) error {
	var err error

	// sql query
	const sqlstr = `UPDATE public.users SET (` +
		`email, first_name, last_name, password, modified_at, created_at` +
		`) = ( ` +
		`$1, $2, $3, $4, $5, $6` +
		`) WHERE id = $7`

	// run query
	XOLog(sqlstr, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt, u.ID)
	_, err = serviceImpl.DB.Exec(sqlstr, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt, u.ID)
	return err
}

// Save saves the User to the database.
/*
	func (u *User) Save(db XODB) error {
		if u.Exists() {
			return u.Update(db)
		}

		return u.Insert(db)
	}
*/

// Upsert performs an upsert for User.
//
// NOTE: PostgreSQL 9.5+ only
func (serviceImpl *UserServiceImpl) UpsertUser(u *User) error {
	var err error

	// sql query
	const sqlstr = `INSERT INTO public.users (` +
		`id, email, first_name, last_name, password, modified_at, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, email, first_name, last_name, password, modified_at, created_at` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.email, EXCLUDED.first_name, EXCLUDED.last_name, EXCLUDED.password, EXCLUDED.modified_at, EXCLUDED.created_at` +
		`)`

	// run query
	XOLog(sqlstr, u.ID, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt)
	_, err = serviceImpl.DB.Exec(sqlstr, u.ID, u.Email, u.FirstName, u.LastName, u.Password, u.ModifiedAt, u.CreatedAt)
	if err != nil {
		return err
	}

	return nil
}

// Delete deletes the User from the database.
func (serviceImpl *UserServiceImpl) DeleteUser(u *User) error {
	var err error

	// sql query
	const sqlstr = `DELETE FROM public.users WHERE id = $1`

	// run query
	XOLog(sqlstr, u.ID)
	_, err = serviceImpl.DB.Exec(sqlstr, u.ID)
	if err != nil {
		return err
	}

	return nil
}

// GetAllUsers returns all rows from 'public.users',
// ordered by "created_at" in descending order.
func (serviceImpl *UserServiceImpl) GetAllUsers() ([]*User, error) {
	const sqlstr = `SELECT ` +
		`*` +
		`FROM public.users`

	q, err := serviceImpl.DB.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Email, &u.FirstName, &u.LastName, &u.Password, &u.ModifiedAt, &u.CreatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &u)
	}

	return res, nil
}

// GetChunkedUsers returns pagingated rows from 'public.users',
// ordered by "created_at" in descending order.
func (serviceImpl *UserServiceImpl) GetChunkedUsers(limit int, offset int) ([]*User, error) {
	const sqlstr = `SELECT ` +
		`*` +
		`FROM public.users LIMIT $1 OFFSET $2`

	q, err := serviceImpl.DB.Query(sqlstr, limit, offset)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Email, &u.FirstName, &u.LastName, &u.Password, &u.ModifiedAt, &u.CreatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &u)
	}

	return res, nil
}

// UserByEmail retrieves a row from 'public.users' as a User.
//
// Generated from index 'users_email_key'.
func UserByEmail(db XODB, email string) (*User, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, email, first_name, last_name, password, modified_at, created_at ` +
		`FROM public.users ` +
		`WHERE email = $1`

	// run query
	XOLog(sqlstr, email)
	u := User{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, email).Scan(&u.ID, &u.Email, &u.FirstName, &u.LastName, &u.Password, &u.ModifiedAt, &u.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &u, nil
}

// UserByID retrieves a row from 'public.users' as a User.
//
// Generated from index 'users_pkey'.
func UserByID(db XODB, id int) (*User, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, email, first_name, last_name, password, modified_at, created_at ` +
		`FROM public.users ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	u := User{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&u.ID, &u.Email, &u.FirstName, &u.LastName, &u.Password, &u.ModifiedAt, &u.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &u, nil
}
